#102 button adjustments
Netcentric/vg-volvotrucks-us-rd pull request #112
Opened 2023-09-20 18:00 UTC by cogniSyb

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #98 #102 #105 

Test URLs:
- Before: https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
- After: https://102-refactor-buttons--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

2023-09-21 08:47 UTC, kesiah requested changes

2023-09-21 08:47 UTC, kesiah commented on styles/styles.css
> +  max-width: 21.5em;
why is needed?

2023-09-21 08:47 UTC, kesiah commented on blocks/v2-video/v2-video.js
> -    button.classList.add(`${blockClass}__button`, 'tertiary');
Hover state is not correct:
<img width="1074" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/3090999/8711ee1b-c4d6-44a9-8213-2884ac61e7fe">

2023-09-21 10:21 UTC, kesiah commented on styles/styles.css
> +  max-width: 21.5em;
😢 
<img width="548" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/3090999/008746c8-9599-4d62-b367-6cbdcaab4727">

2023-09-21 12:11 UTC, Lakshmishri approved these changes

2023-09-21 12:46 UTC, kesiah requested changes

2023-09-21 12:46 UTC, kesiah commented on styles/styles.css
> +  text-transform: uppercase;
It was decided at the beginning of the project that the uppercase will be editor decision. Did this decision change? Now ALL buttons will have uppercase?

2023-09-21 12:46 UTC, kesiah commented on styles/styles.css
> +  height: 40px;
I don't think `height` override is needed.

2023-09-22 07:56 UTC, kesiah approved these changes

2023-09-22 09:19 UTC, merged