#129 Remove empty space between trucks lineup and dealer locator section
Netcentric/vg-volvotrucks-us-rd pull request #139
Opened 2023-09-28 13:52 UTC by TomaszDziezykNetcentric

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #129 

Test URLs:
- Before: https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/
- After: https://129-truck-lineup-space--vg-volvotrucks-us-rd--netcentric.hlx.page/

2023-09-28 16:22 UTC, kesiah commented
I would do:
```
.section:has(+ .v2-dealer-locator-teaser-container) {
    padding-bottom: 0;
}
```

So you can prevent more blocks, not only dealer locator.

2023-09-29 09:09 UTC, cogniSyb requested changes

2023-09-29 09:41 UTC, TomaszDziezykNetcentric commented on blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.css
Updated

2023-09-29 11:30 UTC, cogniSyb approved these changes

2023-09-29 11:59 UTC, Lakshmishri approved these changes

2023-09-29 12:00 UTC, merged