156 pause button for autoplay
Netcentric/vg-volvotrucks-us-rd pull request #174
Opened 2023-10-10 10:54 UTC by markovukiceviccn

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #156 

Test URLs:
- Before: https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/
- After: https://156-pause-button-for-autoplay--vg-volvotrucks-us-rd--netcentric.hlx.page/

2023-10-10 12:32 UTC, TomaszDziezykNetcentric requested changes

2023-10-10 12:32 UTC, TomaszDziezykNetcentric commented on blocks/v2-hero/v2-hero.js
> +    playPauseButton.setAttribute('aria-label', 'Pause video');
Could you use `getTextLabel`?

2023-10-10 12:32 UTC, TomaszDziezykNetcentric commented on blocks/v2-hero/v2-hero.js
> +        playPauseButton.setAttribute('aria-label', 'Play video');
Could you use getTextLabel?

2023-10-10 12:32 UTC, TomaszDziezykNetcentric commented on blocks/v2-hero/v2-hero.js
> +        playPauseButton.setAttribute('aria-label', 'Pause video');
Could you use getTextLabel?

2023-10-11 11:43 UTC, markovukiceviccn commented on blocks/v2-hero/v2-hero.js
>      block.prepend(video);
Playsinline and loop attributes has been added.

2023-10-11 11:43 UTC, markovukiceviccn commented on blocks/v2-hero/v2-hero.js
> +        playPauseButton.setAttribute('aria-label', 'Pause video');
getTextLabel has been utilised.

2023-10-11 11:44 UTC, markovukiceviccn commented on blocks/v2-hero/v2-hero.css
> +  width: 32px;
Support for the "fat fingers" has been added.

2023-10-11 11:51 UTC, TomaszDziezykNetcentric approved these changes

2023-10-11 11:54 UTC, merged