Media with tabs block
Netcentric/vg-volvotrucks-us-rd pull request #254
Opened 2023-11-15 11:46 UTC by SantiagoHomps-NC

Fix #89

Test URLs:
- Before: https://main--vg-volvotrucks-us--hlxsites.hlx.page/drafts/shomps/redesign/media-with-tabs
- After: https://89-media-with-tabs--vg-volvotrucks-us--hlxsites.hlx.page/drafts/shomps/redesign/media-with-tabs

2023-11-16 10:03 UTC, cogniSyb requested changes

2023-11-16 13:16 UTC, cogniSyb requested changes

2023-11-16 13:31 UTC, taimurCognizant commented
@SantiagoHomps-NC the components should have 3 variations with white, gray and black backgrounds. Add more blocks for those as well. Figma reference https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=1790-15933&mode=design&t=u2O1wEzS12J2lQ7g-0

2023-11-17 09:14 UTC, cogniSyb requested changes

2023-11-17 14:48 UTC, cogniSyb requested changes

2023-11-17 14:49 UTC, cogniSyb requested changes

2023-11-17 15:14 UTC, cogniSyb approved these changes

2023-11-17 15:55 UTC, taimurCognizant approved these changes

2023-11-17 15:59 UTC, merged