truck inline block
Netcentric/vg-volvotrucks-us-rd pull request #32
Opened 2023-08-07 16:50 UTC by kesiah

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #16

Test URLs:
- Before: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/
- After: https://16-trucks-lineup--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/

2023-08-09 12:52 UTC, cogniSyb requested changes

2023-08-09 12:52 UTC, cogniSyb commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  padding: 0 35px;
Changing this to `padding: 2px 35px` would make the button focus state properly visible

2023-08-09 12:52 UTC, cogniSyb commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  margin: 35px 0;
Could we use here (and on following line) 32px instead?

2023-08-09 12:52 UTC, cogniSyb commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  margin: 0 15px;
Could we use 16px here instead?

2023-08-09 12:52 UTC, cogniSyb commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  text-wrap: balance;
Should get a max-width. Around 400px?

2023-08-10 07:26 UTC, cogniSyb approved these changes
I’ve opened issue #36 to do the finishing touch on some visual details of this component. For now this PR is approved :)

2023-08-10 08:19 UTC, TomaszDziezykNetcentric requested changes

2023-08-10 08:19 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +    button.addEventListener('click', () => clickHandler.call(this, i));
`this` for the arrow function is undefined. Why not just call the `clickHandler(tabItems, i)`?

2023-08-10 08:19 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +          left: `${e.currentTarget.getBoundingClientRect().x + tabNavigation.scrollLeft}px`,
A small simplification:
```
const {x, scrollLeft, width} = e.currentTarget.getBoundingClientRect();
Object.assign(navigationLine.style, {
    left: `${x + scrollLeft}px`,
    width:  `${width}px`
}
```

2023-08-10 08:19 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +            left: `${activeItem.getBoundingClientRect().x + tabNavigation.scrollLeft}px`,
Simplification as above:
```
const {x, scrollLeft, width} = activeItem.getBoundingClientRect();
Object.assign(navigationLine.style, {
    left: `${x + scrollLeft}px`,
    width:  `${width}px`
}
```

2023-08-10 08:19 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +      left: `${activeNavigationItem.getBoundingClientRect().x + navigation.scrollLeft}px`,
As above code simplification:
```
const {x, scrollLeft, widht} = activeNavigationItem.getBoundingClientRect();
```

2023-08-10 08:19 UTC, TomaszDziezykNetcentric commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
> +      // buttonLink.classList.remove('primary');
Please remove commented code

2023-08-10 09:41 UTC, kesiah commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  text-transform: uppercase;
In this case, I'm not sure, we decided on this approach for the buttons, but also for the navigation bar items?
wdyt @cogniSyb ?

2023-08-10 09:55 UTC, cogniSyb commented on blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
> +  text-transform: uppercase;
In this case it’s a design decision that the buttons will always be capitalised. At least for this component. If this block would be created as reusable (tabbed) component, then I would’ve opted indeed for letting the content editor decide.

2023-08-10 10:46 UTC, TomaszDziezykNetcentric approved these changes

2023-08-10 10:52 UTC, merged