47 section background colour
Netcentric/vg-volvotrucks-us-rd pull request #77
Opened 2023-08-29 13:47 UTC by avinashNChavan

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #47 

Test URLs:
- Before: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/
- After: https://47-section-background-colour--vg-volvotrucks-us-rd--netcentric.hlx.page/

2023-08-30 04:22 UTC, kesiah commented on styles/styles.css
> +.section-dark {
yes, please use `section--grey`, so we make sure we are using modifiers

2023-08-30 04:28 UTC, kesiah commented on styles/styles.css
> +.section-dark {
Also, I'm using `dark` class in the section to change the colour of the text in Hero and Banner blocks, could we use `black` instead for the black background (#141414) and grey for the other one (#F7F7F7)?

2023-08-31 08:29 UTC, avinashNChavan commented on styles/styles.css
> +.section-dark {
Updated

2023-08-31 08:29 UTC, avinashNChavan commented on styles/styles.css
> +.section-darkgrey {
Updated

2023-08-31 10:11 UTC, TomaszDziezykNetcentric requested changes

2023-08-31 10:11 UTC, TomaszDziezykNetcentric commented on scripts/scripts.js
> +    // console.log(main.querySelectorAll(':scope > .section[data-background]'));
please remove commented code

2023-08-31 11:56 UTC, Lakshmishri commented on scripts/scripts.js
> +      const picture = createOptimizedPicture(src, '', false);
This is existing function which is being modified to accommodate the new background color changes. There are places where background images is used in current site, so we shouldn't remove that class

2023-08-31 13:57 UTC, avinashNChavan commented on styles/styles.css
> +.section--grey {
Updated

2023-08-31 13:57 UTC, avinashNChavan commented on styles/styles.css
>  .redesign-v2 button.tertiary {
Updated

2023-08-31 13:57 UTC, avinashNChavan commented on blocks/v2-dealer-locator-teaser/v2-dealer-locator-teaser.css
> +.v2-dlt__content .icon svg {
Updated

2023-09-01 06:15 UTC, avinashNChavan commented on styles/styles.css
> +.section--grey {
Updated

2023-09-01 06:15 UTC, avinashNChavan commented on styles/styles.css
> +  --card-background: var(--c-grey-900);
Updated

2023-09-01 08:22 UTC, closed without merging