V2 components adjust design depending on section color
Netcentric/vg-volvotrucks-us-rd pull request #81
Opened 2023-09-06 04:24 UTC by kesiah

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/section-background
- After: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/section-background

Homepage:
https://47-section-metadata-new--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/index-dark
https://47-section-metadata-new--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/index-gray
https://47-section-metadata-new--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/index

PDP page:
https://47-section-metadata-new--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/pdp-dark
https://47-section-metadata-new--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/pdp-gray
https://47-section-metadata-new--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/pdp

2023-09-07 08:06 UTC, TomaszDziezykNetcentric requested changes, later dismissed

2023-09-12 15:31 UTC, kesiah commented on scripts/scripts.js
>    main.querySelectorAll(':scope > .section[data-background]').forEach((section) => {
done!

2023-09-13 07:46 UTC, cogniSyb approved these changes

2023-09-13 11:30 UTC, markovukiceviccn approved these changes

2023-09-13 11:31 UTC, merged

2023-09-13 11:32 UTC, TomaszDziezykNetcentric approved these changes