43 newsletter
Netcentric/vg-volvotrucks-us-rd pull request #96
Opened 2023-09-15 17:25 UTC by kesiah

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #43

Test URLs:
- Before: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/newsletter
- After: https://43-newsletter--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/newsletter

Extra information: 
- There is no success/error message currently implemented
- Pardot allows setting a success location and error location, by default this field is fulfilled with "Referrer page". Or manually adding an absolute path to those fields.
- If we want a "thank you page" it needs to be created in Franklin and add the path in "Success location" field in Pardot.
- If we want to show a "Thank you message" in the form section, IN A FURTHER STORY. Pardot success location field needs to be configured manually providing extra information as query params `"http://www.myurl.com/?formName=XXX&formResponse=success"` & error location set to `"http://www.myurl.com/?formName=XXX&formResponse=error"` so from the form we can detect the query params and show the message accordingly.
- How Form handler works? We create a form with the specific path (form handler url) in the action field. Once the form is sent, Pardot saves the data and redirect the page to the success location. Fields in the form need to match with the ones created in Pardot (ask the Pardot admin).

Pardot options screenshot:
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/3090999/4668f34c-c205-492b-a43d-782dd301091a)
**Careful!**
Data forwarding fields needs to be unselected!!!!!!
What happens if it is selected?
Franklin does not work with it active. What it does internally is: we do a call to form handler with the necessary body, pardot saves the data and creates another form with action to "success_location" providing as fields the ones we send, and the form is submitted automatically, as a result, Franklin gets a request to open the page with a POST method and fails. Even changing Franklin allowed headers, it does not work.

Form submitted from Pardot to Franklin
![image (1)](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/3090999/0b2315ab-1de5-4b95-a4ec-0f38bb615dfa)

Franklin response to Pardot form:
![image (2)](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/3090999/33f503d5-38bc-4820-840b-f84753cceb87)

2023-09-18 07:37 UTC, markovukiceviccn approved these changes

2023-09-18 18:01 UTC, cogniSyb requested changes

2023-09-19 07:17 UTC, kesiah commented on blocks/v2-forms/forms/subscribe.js
> +    <input type="email" name="email" autocomplete="off" placeholder=" " required />
fixed! Good catch

2023-09-19 15:10 UTC, cogniSyb approved these changes

2023-09-20 08:47 UTC, merged